server:
  port: 8081

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: rabbitmq-service
  profiles:
    include: toggle

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

service:
  paths:
    wallet:
      url: http://localhost:8080
      method: /wallet/balance

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 10
        slowCallDurationThreshold: 4s
        slowCallRateThreshold: 90
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        minimumNumberOfCalls: 10
    instances:
      getBalanceCircuitBreaker:
        baseConfig: default
        failureRateThreshold: 3
