server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: kafka-service-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: ru.gpb.tech.mqrestadapter.model
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

service:
  paths:
    wallet:
      url: http://localhost:8080
      method: /wallet/balance

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 10
        slowCallDurationThreshold: 4s
        slowCallRateThreshold: 90
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        minimumNumberOfCalls: 10
    instances:
      getBalanceCircuitBreaker:
        baseConfig: default
        failureRateThreshold: 3
