spring:
  application:
    name: rest-service
  datasource:
    url: jdbc:postgresql://localhost:5432/education
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
      schema: gpb
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS "gpb";
    # TODO перенести в хранилище секретов
    password: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: false